version: "3.8"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: template
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  web:
    build: .
    depends_on:
      - db
    ports:
      - "5000:8080"