version: "3.8"
services:
  db:
    image: postgres:14.4
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: main
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
      - ./pgdata:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
  web:
    environment:
      - ENVIRONMENT=development
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
