version: "3.8"
services:
  db:
    container_name: db
    image: postgres:14.4-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: main
    volumes: # Do these work on windows?
      - ./db/database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
      - ./db/pgdata:/var/lib/postgresql/data

  api:
    container_name: api
    environment:
      - ENVIRONMENT=development
    build:
      dockerfile: Dockerfile
      context: ./api
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - /api/node_modules
      # - ./client:/app

  client:
    container_name: client
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      # - ./:/client
      - /client/node_modules
    ports:
      - "8000:80" # External:Internal
    # stdin_open: true
    # tty: true
